import { type Result, err, ok, platformError } from "@ai-platform-core/kernel";

export interface StorageRecord<T extends Readonly<Record<string, unknown>>> { readonly id:string; readonly value:T; readonly version:number; readonly updatedAt:Date; }
export interface KeyValueStore<T extends Readonly<Record<string, unknown>>> { readonly put:(id:string,value:T)=>Promise<Result<StorageRecord<T>>>; readonly get:(id:string)=>Promise<Result<StorageRecord<T>>>; readonly list:()=>Promise<Result<readonly StorageRecord<T>[]>>; readonly delete:(id:string)=>Promise<Result<void>>; }
export const createMemoryKeyValueStore=<T extends Readonly<Record<string,unknown>>>():KeyValueStore<T>=>{const records=new Map<string,StorageRecord<T>>();return{put:async(id,value)=>{const current=records.get(id),record={id,value,version:current===undefined?1:current.version+1,updatedAt:new Date()};records.set(id,record);return ok(record)},get:async id=>{const record=records.get(id);return record===undefined?err(platformError("STORAGE_RECORD_NOT_FOUND",`Storage record '${id}' was not found.`)):ok(record)},list:async()=>ok([...records.values()]),delete:async id=>{records.delete(id);return ok(undefined)}}};
export interface D1PreparedStatementLike { bind(...values:unknown[]):D1PreparedStatementLike; first<T=Record<string,unknown>>():Promise<T|null>; all<T=Record<string,unknown>>():Promise<{results:T[]}>; run():Promise<unknown>; }
export interface D1DatabaseLike { prepare(query:string):D1PreparedStatementLike; }
interface D1Row { id:string; value_json:string; version:number; updated_at:string; }
export const createD1KeyValueStore=<T extends Readonly<Record<string,unknown>>>(db:D1DatabaseLike,namespace:string):KeyValueStore<T>=>{const decode=(row:D1Row):StorageRecord<T>=>({id:row.id,value:JSON.parse(row.value_json) as T,version:row.version,updatedAt:new Date(row.updated_at)});return{put:async(id,value)=>{try{const now=new Date().toISOString();await db.prepare("INSERT INTO platform_kv(namespace,id,value_json,version,updated_at) VALUES(?,?,?,?,?) ON CONFLICT(namespace,id) DO UPDATE SET value_json=excluded.value_json,version=platform_kv.version+1,updated_at=excluded.updated_at").bind(namespace,id,JSON.stringify(value),1,now).run();const row=await db.prepare("SELECT id,value_json,version,updated_at FROM platform_kv WHERE namespace=? AND id=? LIMIT 1").bind(namespace,id).first<D1Row>();return row?ok(decode(row)):err(platformError("STORAGE_WRITE_FAILED",`Storage record '${id}' could not be read after write.`))}catch{return err(platformError("STORAGE_WRITE_FAILED",`Storage record '${id}' could not be persisted.`))}},get:async id=>{try{const row=await db.prepare("SELECT id,value_json,version,updated_at FROM platform_kv WHERE namespace=? AND id=? LIMIT 1").bind(namespace,id).first<D1Row>();return row?ok(decode(row)):err(platformError("STORAGE_RECORD_NOT_FOUND",`Storage record '${id}' was not found.`))}catch{return err(platformError("STORAGE_READ_FAILED",`Storage record '${id}' could not be read.`))}},list:async()=>{try{const rows=(await db.prepare("SELECT id,value_json,version,updated_at FROM platform_kv WHERE namespace=? ORDER BY updated_at DESC").bind(namespace).all<D1Row>()).results;return ok(rows.map(decode))}catch{return err(platformError("STORAGE_READ_FAILED",`Storage namespace '${namespace}' could not be listed.`))}},delete:async id=>{try{await db.prepare("DELETE FROM platform_kv WHERE namespace=? AND id=?").bind(namespace,id).run();return ok(undefined)}catch{return err(platformError("STORAGE_DELETE_FAILED",`Storage record '${id}' could not be deleted.`))}}};};
export interface EnvironmentReader { readonly get:(key:string)=>Result<string>; }
export const createEnvironmentReader=(env:Readonly<Record<string,string|undefined>>):EnvironmentReader=>({get:key=>{const value=env[key];return value===undefined?err(platformError("ENVIRONMENT_VALUE_NOT_FOUND",`Environment value '${key}' was not found.`)):ok(value)}});
