import type { Activity, ActivityRepository } from "@ai-platform-core/activity";
import { createStoredAnalyticsRepository, type StoredActivityFeedback, type StoredActivityOutcome, type StoredUsageRecord } from "@ai-platform-core/analytics";
import { createClientRegistry } from "@ai-platform-core/client";
import type { DomainEvent, EventQuery, EventStore } from "@ai-platform-core/event";
import { err, ok, platformError, UUID } from "@ai-platform-core/kernel";
import { createD1KeyValueStore, type D1DatabaseLike } from "@ai-platform-core/storage";
import { createPlatformRuntime, createPromptTemplateRuntime, createStoredPromptTemplateRepository, type PlatformRuntime, type StoredPromptTemplate } from "./index.js";

interface StoredActivity extends Readonly<Record<string,unknown>> { id:string;request:Activity["request"];status:Activity["status"];result?:Activity["result"];outcome?:Activity["outcome"];feedback?:Activity["feedback"];createdAt:string;updatedAt:string; }
interface StoredDomainEvent extends Readonly<Record<string,unknown>> { id:string;type:string;aggregateId:string;version:number;occurredAt:string;payload:Readonly<Record<string,unknown>>;metadata:Readonly<Record<string,unknown>>; }
const toStored=(a:Activity):StoredActivity=>({id:a.id.value,request:a.request,status:a.status,...(a.result===undefined?{}:{result:a.result}),...(a.outcome===undefined?{}:{outcome:a.outcome}),...(a.feedback===undefined?{}:{feedback:a.feedback}),createdAt:a.createdAt.toISOString(),updatedAt:a.updatedAt.toISOString()});
const fromStored=(a:StoredActivity):Activity=>({id:new UUID(a.id),request:a.request,status:a.status,...(a.result===undefined?{}:{result:a.result}),...(a.outcome===undefined?{}:{outcome:a.outcome}),...(a.feedback===undefined?{}:{feedback:a.feedback}),createdAt:new Date(a.createdAt),updatedAt:new Date(a.updatedAt)});
const createStoredActivityRepository=(db:D1DatabaseLike):ActivityRepository=>{const store=createD1KeyValueStore<StoredActivity>(db,"activities");return{save:async activity=>{const saved=await store.put(activity.id.value,toStored(activity));return saved.ok?ok(activity):err(saved.error)},get:async id=>{const record=await store.get(id);return record.ok?ok(fromStored(record.value.value)):err(platformError("ACTIVITY_NOT_FOUND",`Activity '${id}' was not found.`))},list:async()=>{const records=await store.list();return records.ok?ok(records.value.map(r=>fromStored(r.value))):err(records.error)}}};
const toStoredEvent=(event:DomainEvent):StoredDomainEvent=>({id:event.id.value,type:event.type,aggregateId:event.aggregateId.value,version:event.version,occurredAt:event.occurredAt.toISOString(),payload:event.payload,metadata:event.metadata});
const fromStoredEvent=(event:StoredDomainEvent):DomainEvent=>({id:new UUID(event.id),type:event.type,aggregateId:new UUID(event.aggregateId),version:event.version,occurredAt:new Date(event.occurredAt),payload:event.payload,metadata:event.metadata});
const matchesEventQuery=(event:DomainEvent,filter:EventQuery):boolean=>{if(filter.aggregateId&&!event.aggregateId.equals(filter.aggregateId))return false;if(filter.type&&event.type!==filter.type)return false;if(filter.types&&!filter.types.includes(event.type))return false;if(filter.from&&event.occurredAt.getTime()<filter.from.getTime())return false;if(filter.to&&event.occurredAt.getTime()>filter.to.getTime())return false;return true};
const createStoredEventStore=(db:D1DatabaseLike):EventStore=>{const store=createD1KeyValueStore<StoredDomainEvent>(db,"events");return{append:async events=>{for(const event of events){const saved=await store.put(event.id.value,toStoredEvent(event));if(!saved.ok)return err(saved.error)}return ok(undefined)},load:async aggregateId=>{const records=await store.list();return records.ok?ok(records.value.map(r=>fromStoredEvent(r.value)).filter(event=>event.aggregateId.equals(aggregateId))):err(records.error)},query:async(filter={})=>{const records=await store.list();return records.ok?ok(records.value.map(r=>fromStoredEvent(r.value)).filter(event=>matchesEventQuery(event,filter))):err(records.error)},all:async()=>{const records=await store.list();return records.ok?ok(records.value.map(r=>fromStoredEvent(r.value))):err(records.error)}}};
export interface CloudflareRuntimeOptions { readonly db:D1DatabaseLike; }
export const createCloudflarePlatformRuntime=(options:CloudflareRuntimeOptions):PlatformRuntime=>{const usage=createD1KeyValueStore<StoredUsageRecord>(options.db,"analytics.usage"),outcomes=createD1KeyValueStore<StoredActivityOutcome>(options.db,"analytics.outcomes"),feedback=createD1KeyValueStore<StoredActivityFeedback>(options.db,"analytics.feedback"),promptStore=createD1KeyValueStore<StoredPromptTemplate>(options.db,"prompt.templates"),storage=createD1KeyValueStore<Readonly<Record<string,unknown>>>(options.db,"runtime.storage"),events=createStoredEventStore(options.db),clients=createClientRegistry();const registered=clients.register({id:"production-e2e",name:"Production E2E",type:"api",version:"1",provider:"echo",defaultModel:"default",capabilities:["production.echo"],knowledge:[],analytics:true});if(!registered.ok)throw new Error(registered.error.message);return createPlatformRuntime({activityRepository:createStoredActivityRepository(options.db),analytics:createStoredAnalyticsRepository({usage,outcomes,feedback}),clients,events,prompt:createPromptTemplateRuntime(createStoredPromptTemplateRepository(promptStore)),storage});};
